theme: jekyll-theme-slate
title: Christo Staszewski
description: <a href="https://cjstas.github.io/Contact" style="color:gray;text-decoration:none;">Contact</a> <a href="https://cjstas.github.io/About" style="color:gray;text-decoration=none;">About</a>
