theme: jekyll-theme-slate
title: Christo Staszewski
description: <style>
a:link {
  color: white;
  background-color: transparent;
  text-decoration: none;
}

a:visited {
  color: white;
  background-color: transparent;
  text-decoration: none;
}

a:hover {
  color: gray;
  background-color: transparent;
  text-decoration: none;
}

a:active {
  color: white;
  background-color: transparent;
  text-decoration: none;
}

</style><a href="https://cjstas.github.io/Contact">Contact Me</a>
