theme: jekyll-theme-slate
title: Christo Staszewski
description: <a href="https://cjstas.github.io/Contact" style="color:gray;">Contact</a><p style="display:inline">&nbsp;&nbsp;</p> <a href="https://cjstas.github.io/About" style="color:gray;">About</a>
