theme: jekyll-theme-slate
title: Christo Staszewski
description: <a href="https://cjstas.github.io/Contact" style = "text-decoration: none;color: white;">Contact Me</a><a href="https://cjstas.github.io/About">About Me</a>
